DOMAIN_MAP: dict[str, str] = {
    # Video Streaming
    "youtube.com": "YouTube",
    "googlevideo.com": "YouTube",
    "ytimg.com": "YouTube",
    "youtu.be": "YouTube",
    "netflix.com": "Netflix",
    "nflxvideo.net": "Netflix",
    "nflximg.net": "Netflix",
    "nflxso.net": "Netflix",
    "disneyplus.com": "Disney+",
    "disney-plus.net": "Disney+",
    "bamgrid.com": "Disney+",
    "hulu.com": "Hulu",
    "hulustream.com": "Hulu",
    "primevideo.com": "Amazon Prime Video",
    "aiv-cdn.net": "Amazon Prime Video",
    "twitch.tv": "Twitch",
    "ttvnw.net": "Twitch",
    "jtvnw.net": "Twitch",

    # Social Media
    "facebook.com": "Facebook",
    "fbcdn.net": "Facebook",
    "fb.com": "Facebook",
    "instagram.com": "Instagram",
    "cdninstagram.com": "Instagram",
    "twitter.com": "X (Twitter)",
    "x.com": "X (Twitter)",
    "twimg.com": "X (Twitter)",
    "tiktok.com": "TikTok",
    "tiktokcdn.com": "TikTok",
    "musical.ly": "TikTok",
    "snapchat.com": "Snapchat",
    "snap.com": "Snapchat",
    "sc-cdn.net": "Snapchat",
    "reddit.com": "Reddit",
    "redd.it": "Reddit",
    "redditstatic.com": "Reddit",
    "linkedin.com": "LinkedIn",
    "licdn.com": "LinkedIn",
    "pinterest.com": "Pinterest",
    "pinimg.com": "Pinterest",

    # Messaging
    "whatsapp.com": "WhatsApp",
    "whatsapp.net": "WhatsApp",
    "telegram.org": "Telegram",
    "t.me": "Telegram",
    "signal.org": "Signal",
    "discord.com": "Discord",
    "discordapp.com": "Discord",
    "discord.gg": "Discord",

    # Video Conferencing
    "zoom.us": "Zoom",
    "zoomgov.com": "Zoom",
    "teams.microsoft.com": "Microsoft Teams",
    "teams.live.com": "Microsoft Teams",
    "skype.com": "Skype",

    # Music
    "spotify.com": "Spotify",
    "scdn.co": "Spotify",
    "spotifycdn.com": "Spotify",
    "music.apple.com": "Apple Music",
    "soundcloud.com": "SoundCloud",

    # Cloud & Productivity
    "google.com": "Google",
    "googleapis.com": "Google",
    "gstatic.com": "Google",
    "drive.google.com": "Google Drive",
    "docs.google.com": "Google Docs",
    "dropbox.com": "Dropbox",
    "dropboxapi.com": "Dropbox",
    "onedrive.live.com": "OneDrive",
    "sharepoint.com": "Microsoft 365",
    "office.com": "Microsoft 365",
    "office365.com": "Microsoft 365",
    "outlook.com": "Outlook",
    "outlook.live.com": "Outlook",
    "icloud.com": "iCloud",
    "apple.com": "Apple Services",
    "mzstatic.com": "Apple Services",

    # Gaming
    "steampowered.com": "Steam",
    "steamcommunity.com": "Steam",
    "steamcdn-a.akamaihd.net": "Steam",
    "epicgames.com": "Epic Games",
    "playstation.com": "PlayStation",
    "playstation.net": "PlayStation",
    "xbox.com": "Xbox",
    "xboxlive.com": "Xbox",

    # Shopping
    "amazon.com": "Amazon",
    "amazonws.com": "Amazon",
    "ebay.com": "eBay",

    # News
    "cnn.com": "CNN",
    "bbc.com": "BBC",
    "bbc.co.uk": "BBC",
    "nytimes.com": "NY Times",

    # Developer
    "github.com": "GitHub",
    "githubusercontent.com": "GitHub",
    "gitlab.com": "GitLab",
    "stackoverflow.com": "Stack Overflow",

    # Other / CDN / Infrastructure
    "cloudflare.com": "Cloudflare",
    "cloudflare-dns.com": "Cloudflare",
    "akamai.net": "Akamai CDN",
    "akamaiedge.net": "Akamai CDN",
    "akamaitechnologies.com": "Akamai CDN",
    "akamaihd.net": "Akamai CDN",
    "amazonaws.com": "AWS",
    "aws.amazon.com": "AWS",
    "azure.com": "Microsoft Azure",
    "azure.net": "Microsoft Azure",
    "microsoftonline.com": "Microsoft 365",
    "microsoft.com": "Microsoft 365",
    "msftconnecttest.com": "Microsoft 365",
    "windowsupdate.com": "Windows Update",
    "windows.com": "Windows Update",
    "update.microsoft.com": "Windows Update",
    "digicert.com": "DigiCert",

    # Smart Home / IoT
    "ui.com": "Ubiquiti",
    "ubnt.com": "Ubiquiti",
    "svc.ui.com": "Ubiquiti",
    "ring.com": "Ring",
    "nest.com": "Google Nest",
    "alexa.amazon.com": "Amazon Alexa",
    "avs-alexa-na.amazon.com": "Amazon Alexa",
    "smartthings.com": "SmartThings",
    "philips-hue.com": "Philips Hue",
    "tp-link.com": "TP-Link",
    "roku.com": "Roku",
    "sonos.com": "Sonos",

    # NAS / Storage
    "truenas.com": "TrueNAS",
    "freenas.org": "TrueNAS",
    "ixsystems.com": "TrueNAS",
    "synology.com": "Synology",
    "plex.tv": "Plex",
    "plex.direct": "Plex",

    # DNS / Ad blocking
    "adguard.com": "AdGuard",
    "pihole.net": "Pi-hole",

    # Additional services
    "docker.com": "Docker",
    "docker.io": "Docker",
    "npmjs.org": "npm",
    "npmjs.com": "npm",
    "pypi.org": "PyPI",
    "ubuntu.com": "Ubuntu",
    "canonical.com": "Ubuntu",
    "debian.org": "Debian",

    # IoT / Smart Home additional
    "nanoleaf.me": "Nanoleaf",
    "harmony.com": "Logitech Harmony",
    "myharmony.com": "Logitech Harmony",
    "qustodio.com": "Qustodio",
    "unifi-ai.com": "Ubiquiti",

    # Yahoo
    "yahoo.com": "Yahoo",
    "yahooapis.com": "Yahoo",
    "yimg.com": "Yahoo",

    # Google additional
    "googlehomefoyer-pa.googleapis.com": "Google Home",
    "googlevideo.com": "YouTube",
    "googleusercontent.com": "Google",
    "gvt1.com": "Google",
    "gvt2.com": "Google",

    # Microsoft additional
    "microsoftpersonalcontent.com": "OneDrive",
    "live.com": "Microsoft 365",
    "live.net": "Microsoft 365",
    "msn.com": "Microsoft 365",
    "bing.com": "Bing",
    "msedge.net": "Microsoft Edge",
}

CATEGORY_MAP: dict[str, str] = {
    "YouTube": "streaming",
    "Netflix": "streaming",
    "Disney+": "streaming",
    "Hulu": "streaming",
    "Amazon Prime Video": "streaming",
    "Twitch": "streaming",
    "Facebook": "social",
    "Instagram": "social",
    "X (Twitter)": "social",
    "TikTok": "social",
    "Snapchat": "social",
    "Reddit": "social",
    "LinkedIn": "social",
    "Pinterest": "social",
    "WhatsApp": "messaging",
    "Telegram": "messaging",
    "Signal": "messaging",
    "Discord": "messaging",
    "Zoom": "conferencing",
    "Microsoft Teams": "conferencing",
    "Skype": "conferencing",
    "Spotify": "music",
    "Apple Music": "music",
    "SoundCloud": "music",
    "Google": "productivity",
    "Google Drive": "productivity",
    "Google Docs": "productivity",
    "Dropbox": "productivity",
    "OneDrive": "productivity",
    "Microsoft 365": "productivity",
    "Outlook": "productivity",
    "iCloud": "cloud",
    "Apple Services": "cloud",
    "Steam": "gaming",
    "Epic Games": "gaming",
    "PlayStation": "gaming",
    "Xbox": "gaming",
    "Amazon": "shopping",
    "eBay": "shopping",
    "GitHub": "developer",
    "GitLab": "developer",
    "Stack Overflow": "developer",
    "Docker": "developer",
    "npm": "developer",
    "PyPI": "developer",
    "Akamai CDN": "cloud",
    "Cloudflare": "cloud",
    "Microsoft Azure": "cloud",
    "AWS": "cloud",
    "Windows Update": "productivity",
    "DigiCert": "cloud",
    "Ubiquiti": "cloud",
    "Ring": "smart_home",
    "Google Nest": "smart_home",
    "Amazon Alexa": "smart_home",
    "SmartThings": "smart_home",
    "Philips Hue": "smart_home",
    "TP-Link": "smart_home",
    "Roku": "streaming",
    "Sonos": "music",
    "TrueNAS": "cloud",
    "Synology": "cloud",
    "Plex": "streaming",
    "AdGuard": "cloud",
    "Pi-hole": "cloud",
    "Ubuntu": "developer",
    "Debian": "developer",
    "Nanoleaf": "smart_home",
    "Logitech Harmony": "smart_home",
    "Qustodio": "productivity",
    "Yahoo": "productivity",
    "Google Home": "smart_home",
    "Bing": "productivity",
    "Microsoft Edge": "productivity",
}
